server:
  port: 8080
spring:
  rabbitmq:
    host: "localhost"
    port: "5672"
    username: "guest"
    password: "guest"
    virtual-host: "/"
  application:
    name: "FamilyBasket"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb+srv://Daniel:daniel12345@prueba.f1mg5.mongodb.net/products?retryWrites=true&w=majority"
